# Generated by Django 3.2 on 2023-04-17 15:18

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
